name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ (matrix.python && 'system Python') || 'conda' }}
    runs-on: ${{ matrix.os }}
    env:
      PYTHON: '' # always use Conda.jl, even on Linux when `python`/`python3` is in the PATH
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0'
          - '1.6'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
            coverage: true
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install POT
        run: |
          using PyCall: Conda
          Conda.add("pot"; channel="conda-forge")

          # Workaround for https://github.com/JuliaPy/PyCall.jl/issues/999: Use conda's version of the library
          open(ENV["GITHUB_ENV"], "a") do io
            println(io, "LD_PRELOAD=", joinpath(Conda.ROOTENV, "lib", "libstdc++.so.6"))
          end
        shell: julia --project=. --color=yes {0}
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: ${{ matrix.coverage || false }}
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.coverage
      - uses: codecov/codecov-action@v2
        if: matrix.coverage
        with:
          file: lcov.info
      - uses: coverallsapp/github-action@master
        if: matrix.coverage
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ./lcov.info
