name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ (matrix.python && 'system Python') || 'conda' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6.7'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        python:
          - ''
          - python
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
            coverage: true
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: ${{ matrix.arch }}
        if: matrix.python
      - run: python -m pip install pot
        if: matrix.python
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ${{ matrix.python }}
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: ${{ matrix.coverage || false }}
        env:
          PYTHON: ${{ matrix.python }}
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.coverage
      - uses: codecov/codecov-action@v2
        if: matrix.coverage
        with:
          file: lcov.info
      - uses: coverallsapp/github-action@master
        if: matrix.coverage
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ./lcov.info
