name: JuliaNightly

# Nightly Version of Julia. Runs on PRs and pushes to `master`,
# but seperate workflow to `CI` to avoid failure notifications.

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ (matrix.python && 'system Python') || 'conda' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        python:
          - ''
          - python
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: ${{ matrix.arch }}
        if: matrix.python
      # Limitation of pip: https://pythonot.github.io/index.html#pip-installation
      - run: python -m pip install cython numpy
        if: matrix.python
      - run: python -m pip install pot
        if: matrix.python
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ${{ matrix.python }}
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
        env:
          PYTHON: ${{ matrix.python }}
